


from bs4 import BeautifulSoup
import requests
import bleach


def web_parse(class_num):
    dept_name = ""  # Assuming if in the future we include other departments
    if class_num < 100:
        div = "Lower-Division/CSE-"
    else:
        div = "Upper-Division/CSE-"
    class_num_str = str(class_num)
    url = "https://catalog.ucsc.edu/en/2020-2021/General-Catalog/Courses/CSE-Computer-Science-and-Engineering/" + div + class_num_str
    request_result = requests.get(url)
    request_result.raise_for_status()
    html = BeautifulSoup(request_result.text, 'html.parser')
    for a in html.find_all('a'):        # Removing hyperlinks in text
        a.replaceWithChildren()

    cc = str(html.find_all("span")[5].string).replace("CSE ", '')
    gen_descrip = str(html.find_all("p")[1]).replace("</p>", "").replace("<p>", "")
    quarter_offered = str(html.find_all("p")[4].string).split(", ")
    # prereq = str(html.find_all("p")[2]).replace("</p>", "").replace("<p>", "").replace("Prerequisite(s): ", "")

    return cc, gen_descrip, quarter_offered


CLASSES = {
    "cse20": {
        "cc": web_parse(20)[0],  # Class code (20)
        "availability": 7,
        "prereqs": [],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],  # ['Fall', 'Winter', 'Spring']
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,  # Math is 0, programming is 1
        "time_commit": 2,  # 1= slack, 2= some work, 3= extra work
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "cse30": {
        "cc": web_parse(30)[0],
        "availability": 7,
<<<<<<< HEAD
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
=======
        "prereqs": ["cse20"],
>>>>>>> e629bdf2e7be1ed74f45849b9fcbf2722ffc0816
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "cse12": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "cse16": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "math19a": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "math19b": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "math23a": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "math21": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "cse13": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "cse101": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "cse102": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "cse103": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "cse120": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "cse130": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "cse107": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "cse112": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "core": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
    "ge": {
        "cc": web_parse(30)[0],
        "availability": 7,
        "prereqs": ["cse20", "math19A"],
        "gen_descrip": web_parse(30)[1],
        "difficulty": 4,
        "quarter_offered": web_parse(30)[2],
        "syllabus": [{"quiz": 30}, {"midterm": 30}, {"final": 30}],
        "textbook": "url",
        "haslab": False,
        "ta_helpful": 6,
        "class_type": 1,
        "time_commit": 2,
        "ge_satis": ["mf"],
        "pref_prof": ["Larrabee"],
    },
}
#print(CLASSES.get("cse30").get("cc"))
#print(CLASSES.get("cse30"))
#print(CLASSES.keys())


# Parse GEs from GE list to get the type of GE it contains